### ISSUE TITLE
It seems that the new API stuff is broken.

### ISSUE THREAD

**Issue by petersn** [zbanks/musicazoo#53]
I get 403 Forbiddens from sodalord, and the only results that populate on the website when you type something in are things that might plausibly be in the cache.

EDIT:
I played with it a bit more. It's the case that the /nlp endpoint is giving back errors to everything.

    curl --data '{"cmd": "do","args": {"message": "anaconda"}}' http://musicazoo.mit.edu/nlp --header "Content-Type:text/json"

Yields:

    {"success": false, "error": "HTTP 403: Forbidden"}

**Comment by zbanks** [comment]
Closed; it was an issue w/ my api keys.
