### ISSUE TITLE
"Database locked"

### ISSUE THREAD

**Issue by ervanalb** [zbanks/musicazoo#63]
Workaround: delete database

  File "/home/musicazoo/musicazoo/venv/lib/python2.7/site-packages/shmooze/lib/database.py", line 25, in execute
   return self.conn.execute(_sql_command, kwargs)
OperationalError: database is locked

this was preventing queuing of videos (youtube-dl would fetch, and this error would b e encountered, and the video would not queue.)

**Comment by zbanks** [comment]
https://github.com/zbanks/shmooze/issues/1
